from pathlib import Path

"""Merge the skill suite markdown files into one review document.

Run:
    python export_for_review.py
"""

SKILL_DIRS = [
    "shared-research-context",
    "sector-research",
    "stock-fundamental",
    "research-review",
]

FILE_PRIORITY = ["SKILL.md", "README.md"]

BASE_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = BASE_DIR / "skill_suite_for_review.md"


def collect_md_files(skill_dir_path: Path) -> list[Path]:
    """Collect markdown files with SKILL/README first."""
    all_files = [
        path
        for path in skill_dir_path.rglob("*.md")
        if not any(part.startswith(".") for part in path.parts)
    ]

    def sort_key(path: Path) -> tuple[int, int, str]:
        filename = path.name
        if filename in FILE_PRIORITY:
            return (0, FILE_PRIORITY.index(filename), str(path))
        return (1, 0, str(path))

    return sorted(all_files, key=sort_key)


def main() -> None:
    output_lines = [
        "# Research Skill Suite - Full Review Export",
        "",
        "> Auto-generated by `export_for_review.py` for methodology review.",
        "",
        "---",
    ]

    total_files = 0

    for skill_dir_name in SKILL_DIRS:
        skill_dir_path = BASE_DIR / skill_dir_name
        if not skill_dir_path.exists():
            print(f"[WARN] Missing directory, skipped: {skill_dir_name}")
            continue

        output_lines.extend(["", "", f"# {skill_dir_name}"])

        for filepath in collect_md_files(skill_dir_path):
            relative_path = filepath.relative_to(BASE_DIR)
            try:
                content = filepath.read_text(encoding="utf-8").strip()
            except Exception as exc:
                print(f"[WARN] Failed to read {relative_path}: {exc}")
                continue

            output_lines.extend(
                [
                    "",
                    "",
                    f"## {relative_path.as_posix()}",
                    "",
                    "```",
                    content,
                    "```",
                ]
            )
            total_files += 1
            print(f"[OK] {relative_path.as_posix()}")

    OUTPUT_FILE.write_text("\n".join(output_lines) + "\n", encoding="utf-8")

    file_size_kb = OUTPUT_FILE.stat().st_size / 1024
    print(f"[DONE] Exported {total_files} files")
    print(f"[DONE] Output: {OUTPUT_FILE}")
    print(f"[DONE] Size: {file_size_kb:.1f} KB")


if __name__ == "__main__":
    main()
